  main = ".open-next/worker.js"
  name = "dylmye-me"
  compatibility_date = "2025-11-02"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"